/*
 * Author: Austen Rozanski
 * Class: Data Structures
 * Title: Guessing Game
 * 
 * Date Started: January 29, 2015
 * Date Last Revised: January 31, 2015
 * 
 * 
 * Description of Problem: Write a program that allows the user to guess numbers randomly generated by the computer until they answer correctly.
 * 
 * Outline of the Program: Creates a GuessingGame object to randomly generate some numbers with parameters specified by the user. The user then
 * guesses numbers until all are answered correctly.
 */

import java.util.Scanner;

public class U03A_Austen_Rozanski {

	static Scanner input = new Scanner(System.in);
	
	public static void main(String[] args) {

		//Input total numbers for the game
		System.out.println("Enter the number of numbers to be used in the guessing game:");
		int totalNumbers = input.nextInt();
		
		//Input total range for the numbers in the game
		System.out.println("Enter the maximum range of numbers to be used in the guessing game:");
		int maxRange = input.nextInt();
		
		//GuessingGame object
		GuessingGame game = new GuessingGame(totalNumbers, maxRange);
		
		//Variables for looping and storing player guesses
		boolean correctAnswer = false;
		int[] guesses = new int[totalNumbers];
		
		//Game loop. Loop until player guesses correctly.
		while (correctAnswer == false)
		{
			//Guessing input
			for (int i = 0; i < totalNumbers; i++)
			{
				System.out.println("Please enter guess number " + (i+1) + ":");
				guesses[i] = input.nextInt();
			}
			
			//Output
			correctAnswer = game.GuessNumbers(guesses);
		}
		
		//Close the input scanner
		input.close();
		
	}

}
